#Fill here the Google Maps API keys for your application
#In this sample:
#For development and test, we have only one possible host (localhost:3000), so there is only a single key associated with the mode.
#In production, the app can be accessed through 2 different hosts: thepochisuperstarmegashow.com and exmaple.com. There then needs a 2-key hash. If you deployed to one host, only the API key would be needed (as in development and test).

#Fill here the Google Maps API keys for your application
#In this sample:
#For development and test, we have only one possible host (localhost:3000), so there is only a single key associated with the mode.
#In production, the app can be accessed through 2 different hosts: thepochisuperstarmegashow.com and exmaple.com. There then needs a 2-key hash. If you deployed to one host, only the API key would be needed (as in development and test).

development:
  localhost:
    ABQIAAAABrzcjBtnd5A60MXz76RvwRT-_6zkn5LEgwHEyfdSh3Om8nrHpRT0humti8eEtAkx7NugA4_vcAIG-w 
  'www.ianslocalhost.com':
    ABQIAAAA1ivRtQvYVbYZ3QrelYeurRQL9_mWY-GuBzSGHhit-2AeLYx7HRShC2LUxCPYqC7zX5Ltl5Hz4hM66w  
  '77.86.30.132':
    ABQIAAAABrzcjBtnd5A60MXz76RvwRT-_6zkn5LEgwHEyfdSh3Om8nrHpRT0humti8eEtAkx7NugA4_vcAIG-w
  'sislocalhost.com':
    ABQIAAAA-PFo5_yNImRyNEWN7xBB9BRb9eE4sUsWzpR9IQketKnPmeAQbRTWl4-E31pmN2mhhjOjsmlaqF5xrQ
  'richlocalhost.com':
    ABQIAAAA__SjBnhuaD1oP4botqVOFxTFXS1CeoFsf4HSLjo9sLiTE4EXyxTwtrbRkTiYSywfSbqhbY_iXGWyUA
test:
 ABQIAAAAzMUFFnT9uH0xq39J0Y4kbhTJQa0g3IQ9GZqIMmInSLzwtGDKaBR6j135zrztfTGVOm2QlWnkaidDIQ

#key for http://bta.yoomee.com
production:
 ABQIAAAAhV_1h_KHiNYsGmLoY2LPlRRQvjOtEfKK35q-JHmEMLdpxDkBBRTZWv4Gv16jNxiI76ef5WpipzYpyQ
